#cloud-config
# You will need to edit this file before creating your new servers
users:
  - name: web
    primary_group: web
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed58514 AAAAC3NzaC1lZDI1NTE5AAAAIJ44A7F8D2E1BC093A54A7F8D2E1BC093A5 email@gmail.com

packages:
  - ripgrep
  - rsync
  - nginx
  - ufw

runcmd:
  - sed -i 's/^#\(Storage=auto\)/\1/' /etc/systemd/journald.conf
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - systemctl restart ssh
  - systemctl restart systemd-journald
  - ufw allow ssh
  - ufw allow http
